export const CulturalDayImgs = [
  { src: "/assets/images/cultural-day/1.jpg" },
  { src: "/assets/images/cultural-day/2.jpg" },
  { src: "/assets/images/cultural-day/3.jpg" },
  { src: "/assets/images/cultural-day/4.jpg" },
  { src: "/assets/images/cultural-day/5.jpg" },
  { src: "/assets/images/cultural-day/6.jpg" },
  { src: "/assets/images/cultural-day/7.jpg" },
  { src: "/assets/images/cultural-day/8.jpg" },
  { src: "/assets/images/cultural-day/9.jpg" },
  { src: "/assets/images/cultural-day/10.jpg" },
  { src: "/assets/images/cultural-day/11.jpg" },
  { src: "/assets/images/cultural-day/12.jpg" },
  { src: "/assets/images/cultural-day/13.jpg" },
  { src: "/assets/images/cultural-day/14.jpg" },
  { src: "/assets/images/cultural-day/15.jpg" },
  { src: "/assets/images/cultural-day/16.jpg" },
  { src: "/assets/images/cultural-day/17.jpg" },
  { src: "/assets/images/cultural-day/18.jpg" },
];
